package com.jianxilin.ssm.dao;

import com.jianxilin.ssm.entity.ZcInout;
import com.jianxilin.ssm.entity.ZcInoutExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface ZcInoutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    long countByExample(ZcInoutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int deleteByExample(ZcInoutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int deleteByPrimaryKey(Integer inoutNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int insert(ZcInout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int insertSelective(ZcInout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    List<ZcInout> selectByExampleWithRowbounds(ZcInoutExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    List<ZcInout> selectByExample(ZcInoutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    ZcInout selectByPrimaryKey(Integer inoutNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") ZcInout record, @Param("example") ZcInoutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int updateByExample(@Param("record") ZcInout record, @Param("example") ZcInoutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int updateByPrimaryKeySelective(ZcInout record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int updateByPrimaryKey(ZcInout record);
}