package com.jianxilin.ssm.dao;

import com.jianxilin.ssm.entity.ZcInfo;
import com.jianxilin.ssm.entity.ZcInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface ZcInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    long countByExample(ZcInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int deleteByExample(ZcInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int deleteByPrimaryKey(String zcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int insert(ZcInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int insertSelective(ZcInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    List<ZcInfo> selectByExampleWithRowbounds(ZcInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    List<ZcInfo> selectByExample(ZcInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    ZcInfo selectByPrimaryKey(String zcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") ZcInfo record, @Param("example") ZcInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int updateByExample(@Param("record") ZcInfo record, @Param("example") ZcInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int updateByPrimaryKeySelective(ZcInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int updateByPrimaryKey(ZcInfo record);
}