package com.jianxilin.ssm.dao;

import com.jianxilin.ssm.entity.ZcWx;
import com.jianxilin.ssm.entity.ZcWxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ZcWxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_wx
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    long countByExample(ZcWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_wx
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int deleteByExample(ZcWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_wx
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int deleteByPrimaryKey(Integer repairNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_wx
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int insert(ZcWx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_wx
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int insertSelective(ZcWx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_wx
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    List<ZcWx> selectByExampleWithRowbounds(ZcWxExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_wx
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    List<ZcWx> selectByExample(ZcWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_wx
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    ZcWx selectByPrimaryKey(Integer repairNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_wx
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") ZcWx record, @Param("example") ZcWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_wx
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int updateByExample(@Param("record") ZcWx record, @Param("example") ZcWxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_wx
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int updateByPrimaryKeySelective(ZcWx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_wx
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    int updateByPrimaryKey(ZcWx record);
}