package com.jianxilin.ssm.entity;

public class Comployee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comployee.comployee_no
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String comployeeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comployee.comployee_name
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String comployeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comployee.sex
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comployee.age
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comployee.dept
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String dept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comployee.profession
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String profession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comployee.address
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comployee.phone
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comployee.comployee_status
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String comployeeStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comployee.comployee_no
     *
     * @return the value of comployee.comployee_no
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getComployeeNo() {
        return comployeeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comployee.comployee_no
     *
     * @param comployeeNo the value for comployee.comployee_no
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setComployeeNo(String comployeeNo) {
        this.comployeeNo = comployeeNo == null ? null : comployeeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comployee.comployee_name
     *
     * @return the value of comployee.comployee_name
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getComployeeName() {
        return comployeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comployee.comployee_name
     *
     * @param comployeeName the value for comployee.comployee_name
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setComployeeName(String comployeeName) {
        this.comployeeName = comployeeName == null ? null : comployeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comployee.sex
     *
     * @return the value of comployee.sex
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comployee.sex
     *
     * @param sex the value for comployee.sex
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comployee.age
     *
     * @return the value of comployee.age
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comployee.age
     *
     * @param age the value for comployee.age
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comployee.dept
     *
     * @return the value of comployee.dept
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comployee.dept
     *
     * @param dept the value for comployee.dept
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comployee.profession
     *
     * @return the value of comployee.profession
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comployee.profession
     *
     * @param profession the value for comployee.profession
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comployee.address
     *
     * @return the value of comployee.address
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comployee.address
     *
     * @param address the value for comployee.address
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comployee.phone
     *
     * @return the value of comployee.phone
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comployee.phone
     *
     * @param phone the value for comployee.phone
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comployee.comployee_status
     *
     * @return the value of comployee.comployee_status
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getComployeeStatus() {
        return comployeeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comployee.comployee_status
     *
     * @param comployeeStatus the value for comployee.comployee_status
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setComployeeStatus(String comployeeStatus) {
        this.comployeeStatus = comployeeStatus == null ? null : comployeeStatus.trim();
    }

    @Override
    public String toString() {
        return "Comployee{" +
                "comployeeNo='" + comployeeNo + '\'' +
                ", comployeeName='" + comployeeName + '\'' +
                ", sex='" + sex + '\'' +
                ", age=" + age +
                ", dept='" + dept + '\'' +
                ", profession='" + profession + '\'' +
                ", address='" + address + '\'' +
                ", phone='" + phone + '\'' +
                ", comployeeStatus='" + comployeeStatus + '\'' +
                '}';
    }
}