package com.jianxilin.ssm.entity;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dept
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String dept;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dept
     *
     * @return the value of department.dept
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dept
     *
     * @param dept the value for department.dept
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }
}