package com.jianxilin.ssm.entity;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.userName
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.pwd
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.comployee_no
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String comployeeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.competence
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String competence;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.userName
     *
     * @return the value of user_info.userName
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.userName
     *
     * @param username the value for user_info.userName
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.pwd
     *
     * @return the value of user_info.pwd
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.pwd
     *
     * @param pwd the value for user_info.pwd
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.comployee_no
     *
     * @return the value of user_info.comployee_no
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getComployeeNo() {
        return comployeeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.comployee_no
     *
     * @param comployeeNo the value for user_info.comployee_no
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setComployeeNo(String comployeeNo) {
        this.comployeeNo = comployeeNo == null ? null : comployeeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.competence
     *
     * @return the value of user_info.competence
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getCompetence() {
        return competence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.competence
     *
     * @param competence the value for user_info.competence
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setCompetence(String competence) {
        this.competence = competence == null ? null : competence.trim();
    }
}