package com.jianxilin.ssm.entity;

import java.util.ArrayList;
import java.util.List;

public class ZcInoutExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public ZcInoutExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInoutNoIsNull() {
            addCriterion("inout_no is null");
            return (Criteria) this;
        }

        public Criteria andInoutNoIsNotNull() {
            addCriterion("inout_no is not null");
            return (Criteria) this;
        }

        public Criteria andInoutNoEqualTo(Integer value) {
            addCriterion("inout_no =", value, "inoutNo");
            return (Criteria) this;
        }

        public Criteria andInoutNoNotEqualTo(Integer value) {
            addCriterion("inout_no <>", value, "inoutNo");
            return (Criteria) this;
        }

        public Criteria andInoutNoGreaterThan(Integer value) {
            addCriterion("inout_no >", value, "inoutNo");
            return (Criteria) this;
        }

        public Criteria andInoutNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("inout_no >=", value, "inoutNo");
            return (Criteria) this;
        }

        public Criteria andInoutNoLessThan(Integer value) {
            addCriterion("inout_no <", value, "inoutNo");
            return (Criteria) this;
        }

        public Criteria andInoutNoLessThanOrEqualTo(Integer value) {
            addCriterion("inout_no <=", value, "inoutNo");
            return (Criteria) this;
        }

        public Criteria andInoutNoIn(List<Integer> values) {
            addCriterion("inout_no in", values, "inoutNo");
            return (Criteria) this;
        }

        public Criteria andInoutNoNotIn(List<Integer> values) {
            addCriterion("inout_no not in", values, "inoutNo");
            return (Criteria) this;
        }

        public Criteria andInoutNoBetween(Integer value1, Integer value2) {
            addCriterion("inout_no between", value1, value2, "inoutNo");
            return (Criteria) this;
        }

        public Criteria andInoutNoNotBetween(Integer value1, Integer value2) {
            addCriterion("inout_no not between", value1, value2, "inoutNo");
            return (Criteria) this;
        }

        public Criteria andZcIdIsNull() {
            addCriterion("zc_id is null");
            return (Criteria) this;
        }

        public Criteria andZcIdIsNotNull() {
            addCriterion("zc_id is not null");
            return (Criteria) this;
        }

        public Criteria andZcIdEqualTo(String value) {
            addCriterion("zc_id =", value, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdNotEqualTo(String value) {
            addCriterion("zc_id <>", value, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdGreaterThan(String value) {
            addCriterion("zc_id >", value, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdGreaterThanOrEqualTo(String value) {
            addCriterion("zc_id >=", value, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdLessThan(String value) {
            addCriterion("zc_id <", value, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdLessThanOrEqualTo(String value) {
            addCriterion("zc_id <=", value, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdLike(String value) {
            addCriterion("zc_id like", value, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdNotLike(String value) {
            addCriterion("zc_id not like", value, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdIn(List<String> values) {
            addCriterion("zc_id in", values, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdNotIn(List<String> values) {
            addCriterion("zc_id not in", values, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdBetween(String value1, String value2) {
            addCriterion("zc_id between", value1, value2, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdNotBetween(String value1, String value2) {
            addCriterion("zc_id not between", value1, value2, "zcId");
            return (Criteria) this;
        }

        public Criteria andComployeeNoIsNull() {
            addCriterion("comployee_no is null");
            return (Criteria) this;
        }

        public Criteria andComployeeNoIsNotNull() {
            addCriterion("comployee_no is not null");
            return (Criteria) this;
        }

        public Criteria andComployeeNoEqualTo(String value) {
            addCriterion("comployee_no =", value, "comployeeNo");
            return (Criteria) this;
        }

        public Criteria andComployeeNoNotEqualTo(String value) {
            addCriterion("comployee_no <>", value, "comployeeNo");
            return (Criteria) this;
        }

        public Criteria andComployeeNoGreaterThan(String value) {
            addCriterion("comployee_no >", value, "comployeeNo");
            return (Criteria) this;
        }

        public Criteria andComployeeNoGreaterThanOrEqualTo(String value) {
            addCriterion("comployee_no >=", value, "comployeeNo");
            return (Criteria) this;
        }

        public Criteria andComployeeNoLessThan(String value) {
            addCriterion("comployee_no <", value, "comployeeNo");
            return (Criteria) this;
        }

        public Criteria andComployeeNoLessThanOrEqualTo(String value) {
            addCriterion("comployee_no <=", value, "comployeeNo");
            return (Criteria) this;
        }

        public Criteria andComployeeNoLike(String value) {
            addCriterion("comployee_no like", value, "comployeeNo");
            return (Criteria) this;
        }

        public Criteria andComployeeNoNotLike(String value) {
            addCriterion("comployee_no not like", value, "comployeeNo");
            return (Criteria) this;
        }

        public Criteria andComployeeNoIn(List<String> values) {
            addCriterion("comployee_no in", values, "comployeeNo");
            return (Criteria) this;
        }

        public Criteria andComployeeNoNotIn(List<String> values) {
            addCriterion("comployee_no not in", values, "comployeeNo");
            return (Criteria) this;
        }

        public Criteria andComployeeNoBetween(String value1, String value2) {
            addCriterion("comployee_no between", value1, value2, "comployeeNo");
            return (Criteria) this;
        }

        public Criteria andComployeeNoNotBetween(String value1, String value2) {
            addCriterion("comployee_no not between", value1, value2, "comployeeNo");
            return (Criteria) this;
        }

        public Criteria andOutTimeIsNull() {
            addCriterion("out_time is null");
            return (Criteria) this;
        }

        public Criteria andOutTimeIsNotNull() {
            addCriterion("out_time is not null");
            return (Criteria) this;
        }

        public Criteria andOutTimeEqualTo(String value) {
            addCriterion("out_time =", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeNotEqualTo(String value) {
            addCriterion("out_time <>", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeGreaterThan(String value) {
            addCriterion("out_time >", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeGreaterThanOrEqualTo(String value) {
            addCriterion("out_time >=", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeLessThan(String value) {
            addCriterion("out_time <", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeLessThanOrEqualTo(String value) {
            addCriterion("out_time <=", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeLike(String value) {
            addCriterion("out_time like", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeNotLike(String value) {
            addCriterion("out_time not like", value, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeIn(List<String> values) {
            addCriterion("out_time in", values, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeNotIn(List<String> values) {
            addCriterion("out_time not in", values, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeBetween(String value1, String value2) {
            addCriterion("out_time between", value1, value2, "outTime");
            return (Criteria) this;
        }

        public Criteria andOutTimeNotBetween(String value1, String value2) {
            addCriterion("out_time not between", value1, value2, "outTime");
            return (Criteria) this;
        }

        public Criteria andShouldTimeIsNull() {
            addCriterion("should_time is null");
            return (Criteria) this;
        }

        public Criteria andShouldTimeIsNotNull() {
            addCriterion("should_time is not null");
            return (Criteria) this;
        }

        public Criteria andShouldTimeEqualTo(String value) {
            addCriterion("should_time =", value, "shouldTime");
            return (Criteria) this;
        }

        public Criteria andShouldTimeNotEqualTo(String value) {
            addCriterion("should_time <>", value, "shouldTime");
            return (Criteria) this;
        }

        public Criteria andShouldTimeGreaterThan(String value) {
            addCriterion("should_time >", value, "shouldTime");
            return (Criteria) this;
        }

        public Criteria andShouldTimeGreaterThanOrEqualTo(String value) {
            addCriterion("should_time >=", value, "shouldTime");
            return (Criteria) this;
        }

        public Criteria andShouldTimeLessThan(String value) {
            addCriterion("should_time <", value, "shouldTime");
            return (Criteria) this;
        }

        public Criteria andShouldTimeLessThanOrEqualTo(String value) {
            addCriterion("should_time <=", value, "shouldTime");
            return (Criteria) this;
        }

        public Criteria andShouldTimeLike(String value) {
            addCriterion("should_time like", value, "shouldTime");
            return (Criteria) this;
        }

        public Criteria andShouldTimeNotLike(String value) {
            addCriterion("should_time not like", value, "shouldTime");
            return (Criteria) this;
        }

        public Criteria andShouldTimeIn(List<String> values) {
            addCriterion("should_time in", values, "shouldTime");
            return (Criteria) this;
        }

        public Criteria andShouldTimeNotIn(List<String> values) {
            addCriterion("should_time not in", values, "shouldTime");
            return (Criteria) this;
        }

        public Criteria andShouldTimeBetween(String value1, String value2) {
            addCriterion("should_time between", value1, value2, "shouldTime");
            return (Criteria) this;
        }

        public Criteria andShouldTimeNotBetween(String value1, String value2) {
            addCriterion("should_time not between", value1, value2, "shouldTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeIsNull() {
            addCriterion("back_time is null");
            return (Criteria) this;
        }

        public Criteria andBackTimeIsNotNull() {
            addCriterion("back_time is not null");
            return (Criteria) this;
        }

        public Criteria andBackTimeEqualTo(String value) {
            addCriterion("back_time =", value, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeNotEqualTo(String value) {
            addCriterion("back_time <>", value, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeGreaterThan(String value) {
            addCriterion("back_time >", value, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeGreaterThanOrEqualTo(String value) {
            addCriterion("back_time >=", value, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeLessThan(String value) {
            addCriterion("back_time <", value, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeLessThanOrEqualTo(String value) {
            addCriterion("back_time <=", value, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeLike(String value) {
            addCriterion("back_time like", value, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeNotLike(String value) {
            addCriterion("back_time not like", value, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeIn(List<String> values) {
            addCriterion("back_time in", values, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeNotIn(List<String> values) {
            addCriterion("back_time not in", values, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeBetween(String value1, String value2) {
            addCriterion("back_time between", value1, value2, "backTime");
            return (Criteria) this;
        }

        public Criteria andBackTimeNotBetween(String value1, String value2) {
            addCriterion("back_time not between", value1, value2, "backTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zc_inout
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 29 15:27:41 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zc_inout
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}