package com.jianxilin.ssm.entity;

public class ZcInout {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_inout.inout_no
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private Integer inoutNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_inout.zc_id
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String zcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_inout.comployee_no
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String comployeeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_inout.out_time
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String outTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_inout.should_time
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String shouldTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_inout.back_time
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String backTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_inout.inout_no
     *
     * @return the value of zc_inout.inout_no
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public Integer getInoutNo() {
        return inoutNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_inout.inout_no
     *
     * @param inoutNo the value for zc_inout.inout_no
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setInoutNo(Integer inoutNo) {
        this.inoutNo = inoutNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_inout.zc_id
     *
     * @return the value of zc_inout.zc_id
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getZcId() {
        return zcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_inout.zc_id
     *
     * @param zcId the value for zc_inout.zc_id
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setZcId(String zcId) {
        this.zcId = zcId == null ? null : zcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_inout.comployee_no
     *
     * @return the value of zc_inout.comployee_no
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getComployeeNo() {
        return comployeeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_inout.comployee_no
     *
     * @param comployeeNo the value for zc_inout.comployee_no
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setComployeeNo(String comployeeNo) {
        this.comployeeNo = comployeeNo == null ? null : comployeeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_inout.out_time
     *
     * @return the value of zc_inout.out_time
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_inout.out_time
     *
     * @param outTime the value for zc_inout.out_time
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setOutTime(String outTime) {
        this.outTime = outTime == null ? null : outTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_inout.should_time
     *
     * @return the value of zc_inout.should_time
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getShouldTime() {
        return shouldTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_inout.should_time
     *
     * @param shouldTime the value for zc_inout.should_time
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setShouldTime(String shouldTime) {
        this.shouldTime = shouldTime == null ? null : shouldTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_inout.back_time
     *
     * @return the value of zc_inout.back_time
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getBackTime() {
        return backTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_inout.back_time
     *
     * @param backTime the value for zc_inout.back_time
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setBackTime(String backTime) {
        this.backTime = backTime == null ? null : backTime.trim();
    }
}