package com.jianxilin.ssm.entity;

import java.util.ArrayList;
import java.util.List;

public class ZcInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public ZcInfoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andZcIdIsNull() {
            addCriterion("zc_id is null");
            return (Criteria) this;
        }

        public Criteria andZcIdIsNotNull() {
            addCriterion("zc_id is not null");
            return (Criteria) this;
        }

        public Criteria andZcIdEqualTo(String value) {
            addCriterion("zc_id =", value, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdNotEqualTo(String value) {
            addCriterion("zc_id <>", value, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdGreaterThan(String value) {
            addCriterion("zc_id >", value, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdGreaterThanOrEqualTo(String value) {
            addCriterion("zc_id >=", value, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdLessThan(String value) {
            addCriterion("zc_id <", value, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdLessThanOrEqualTo(String value) {
            addCriterion("zc_id <=", value, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdLike(String value) {
            addCriterion("zc_id like", value, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdNotLike(String value) {
            addCriterion("zc_id not like", value, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdIn(List<String> values) {
            addCriterion("zc_id in", values, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdNotIn(List<String> values) {
            addCriterion("zc_id not in", values, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdBetween(String value1, String value2) {
            addCriterion("zc_id between", value1, value2, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcIdNotBetween(String value1, String value2) {
            addCriterion("zc_id not between", value1, value2, "zcId");
            return (Criteria) this;
        }

        public Criteria andZcNoIsNull() {
            addCriterion("zc_no is null");
            return (Criteria) this;
        }

        public Criteria andZcNoIsNotNull() {
            addCriterion("zc_no is not null");
            return (Criteria) this;
        }

        public Criteria andZcNoEqualTo(String value) {
            addCriterion("zc_no =", value, "zcNo");
            return (Criteria) this;
        }

        public Criteria andZcNoNotEqualTo(String value) {
            addCriterion("zc_no <>", value, "zcNo");
            return (Criteria) this;
        }

        public Criteria andZcNoGreaterThan(String value) {
            addCriterion("zc_no >", value, "zcNo");
            return (Criteria) this;
        }

        public Criteria andZcNoGreaterThanOrEqualTo(String value) {
            addCriterion("zc_no >=", value, "zcNo");
            return (Criteria) this;
        }

        public Criteria andZcNoLessThan(String value) {
            addCriterion("zc_no <", value, "zcNo");
            return (Criteria) this;
        }

        public Criteria andZcNoLessThanOrEqualTo(String value) {
            addCriterion("zc_no <=", value, "zcNo");
            return (Criteria) this;
        }

        public Criteria andZcNoLike(String value) {
            addCriterion("zc_no like", value, "zcNo");
            return (Criteria) this;
        }

        public Criteria andZcNoNotLike(String value) {
            addCriterion("zc_no not like", value, "zcNo");
            return (Criteria) this;
        }

        public Criteria andZcNoIn(List<String> values) {
            addCriterion("zc_no in", values, "zcNo");
            return (Criteria) this;
        }

        public Criteria andZcNoNotIn(List<String> values) {
            addCriterion("zc_no not in", values, "zcNo");
            return (Criteria) this;
        }

        public Criteria andZcNoBetween(String value1, String value2) {
            addCriterion("zc_no between", value1, value2, "zcNo");
            return (Criteria) this;
        }

        public Criteria andZcNoNotBetween(String value1, String value2) {
            addCriterion("zc_no not between", value1, value2, "zcNo");
            return (Criteria) this;
        }

        public Criteria andZcNameIsNull() {
            addCriterion("zc_name is null");
            return (Criteria) this;
        }

        public Criteria andZcNameIsNotNull() {
            addCriterion("zc_name is not null");
            return (Criteria) this;
        }

        public Criteria andZcNameEqualTo(String value) {
            addCriterion("zc_name =", value, "zcName");
            return (Criteria) this;
        }

        public Criteria andZcNameNotEqualTo(String value) {
            addCriterion("zc_name <>", value, "zcName");
            return (Criteria) this;
        }

        public Criteria andZcNameGreaterThan(String value) {
            addCriterion("zc_name >", value, "zcName");
            return (Criteria) this;
        }

        public Criteria andZcNameGreaterThanOrEqualTo(String value) {
            addCriterion("zc_name >=", value, "zcName");
            return (Criteria) this;
        }

        public Criteria andZcNameLessThan(String value) {
            addCriterion("zc_name <", value, "zcName");
            return (Criteria) this;
        }

        public Criteria andZcNameLessThanOrEqualTo(String value) {
            addCriterion("zc_name <=", value, "zcName");
            return (Criteria) this;
        }

        public Criteria andZcNameLike(String value) {
            addCriterion("zc_name like", value, "zcName");
            return (Criteria) this;
        }

        public Criteria andZcNameNotLike(String value) {
            addCriterion("zc_name not like", value, "zcName");
            return (Criteria) this;
        }

        public Criteria andZcNameIn(List<String> values) {
            addCriterion("zc_name in", values, "zcName");
            return (Criteria) this;
        }

        public Criteria andZcNameNotIn(List<String> values) {
            addCriterion("zc_name not in", values, "zcName");
            return (Criteria) this;
        }

        public Criteria andZcNameBetween(String value1, String value2) {
            addCriterion("zc_name between", value1, value2, "zcName");
            return (Criteria) this;
        }

        public Criteria andZcNameNotBetween(String value1, String value2) {
            addCriterion("zc_name not between", value1, value2, "zcName");
            return (Criteria) this;
        }

        public Criteria andZcPriceIsNull() {
            addCriterion("zc_price is null");
            return (Criteria) this;
        }

        public Criteria andZcPriceIsNotNull() {
            addCriterion("zc_price is not null");
            return (Criteria) this;
        }

        public Criteria andZcPriceEqualTo(Float value) {
            addCriterion("zc_price =", value, "zcPrice");
            return (Criteria) this;
        }

        public Criteria andZcPriceNotEqualTo(Float value) {
            addCriterion("zc_price <>", value, "zcPrice");
            return (Criteria) this;
        }

        public Criteria andZcPriceGreaterThan(Float value) {
            addCriterion("zc_price >", value, "zcPrice");
            return (Criteria) this;
        }

        public Criteria andZcPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("zc_price >=", value, "zcPrice");
            return (Criteria) this;
        }

        public Criteria andZcPriceLessThan(Float value) {
            addCriterion("zc_price <", value, "zcPrice");
            return (Criteria) this;
        }

        public Criteria andZcPriceLessThanOrEqualTo(Float value) {
            addCriterion("zc_price <=", value, "zcPrice");
            return (Criteria) this;
        }

        public Criteria andZcPriceIn(List<Float> values) {
            addCriterion("zc_price in", values, "zcPrice");
            return (Criteria) this;
        }

        public Criteria andZcPriceNotIn(List<Float> values) {
            addCriterion("zc_price not in", values, "zcPrice");
            return (Criteria) this;
        }

        public Criteria andZcPriceBetween(Float value1, Float value2) {
            addCriterion("zc_price between", value1, value2, "zcPrice");
            return (Criteria) this;
        }

        public Criteria andZcPriceNotBetween(Float value1, Float value2) {
            addCriterion("zc_price not between", value1, value2, "zcPrice");
            return (Criteria) this;
        }

        public Criteria andZcFactoryIsNull() {
            addCriterion("zc_factory is null");
            return (Criteria) this;
        }

        public Criteria andZcFactoryIsNotNull() {
            addCriterion("zc_factory is not null");
            return (Criteria) this;
        }

        public Criteria andZcFactoryEqualTo(String value) {
            addCriterion("zc_factory =", value, "zcFactory");
            return (Criteria) this;
        }

        public Criteria andZcFactoryNotEqualTo(String value) {
            addCriterion("zc_factory <>", value, "zcFactory");
            return (Criteria) this;
        }

        public Criteria andZcFactoryGreaterThan(String value) {
            addCriterion("zc_factory >", value, "zcFactory");
            return (Criteria) this;
        }

        public Criteria andZcFactoryGreaterThanOrEqualTo(String value) {
            addCriterion("zc_factory >=", value, "zcFactory");
            return (Criteria) this;
        }

        public Criteria andZcFactoryLessThan(String value) {
            addCriterion("zc_factory <", value, "zcFactory");
            return (Criteria) this;
        }

        public Criteria andZcFactoryLessThanOrEqualTo(String value) {
            addCriterion("zc_factory <=", value, "zcFactory");
            return (Criteria) this;
        }

        public Criteria andZcFactoryLike(String value) {
            addCriterion("zc_factory like", value, "zcFactory");
            return (Criteria) this;
        }

        public Criteria andZcFactoryNotLike(String value) {
            addCriterion("zc_factory not like", value, "zcFactory");
            return (Criteria) this;
        }

        public Criteria andZcFactoryIn(List<String> values) {
            addCriterion("zc_factory in", values, "zcFactory");
            return (Criteria) this;
        }

        public Criteria andZcFactoryNotIn(List<String> values) {
            addCriterion("zc_factory not in", values, "zcFactory");
            return (Criteria) this;
        }

        public Criteria andZcFactoryBetween(String value1, String value2) {
            addCriterion("zc_factory between", value1, value2, "zcFactory");
            return (Criteria) this;
        }

        public Criteria andZcFactoryNotBetween(String value1, String value2) {
            addCriterion("zc_factory not between", value1, value2, "zcFactory");
            return (Criteria) this;
        }

        public Criteria andZcProducetimeIsNull() {
            addCriterion("zc_produceTime is null");
            return (Criteria) this;
        }

        public Criteria andZcProducetimeIsNotNull() {
            addCriterion("zc_produceTime is not null");
            return (Criteria) this;
        }

        public Criteria andZcProducetimeEqualTo(String value) {
            addCriterion("zc_produceTime =", value, "zcProducetime");
            return (Criteria) this;
        }

        public Criteria andZcProducetimeNotEqualTo(String value) {
            addCriterion("zc_produceTime <>", value, "zcProducetime");
            return (Criteria) this;
        }

        public Criteria andZcProducetimeGreaterThan(String value) {
            addCriterion("zc_produceTime >", value, "zcProducetime");
            return (Criteria) this;
        }

        public Criteria andZcProducetimeGreaterThanOrEqualTo(String value) {
            addCriterion("zc_produceTime >=", value, "zcProducetime");
            return (Criteria) this;
        }

        public Criteria andZcProducetimeLessThan(String value) {
            addCriterion("zc_produceTime <", value, "zcProducetime");
            return (Criteria) this;
        }

        public Criteria andZcProducetimeLessThanOrEqualTo(String value) {
            addCriterion("zc_produceTime <=", value, "zcProducetime");
            return (Criteria) this;
        }

        public Criteria andZcProducetimeLike(String value) {
            addCriterion("zc_produceTime like", value, "zcProducetime");
            return (Criteria) this;
        }

        public Criteria andZcProducetimeNotLike(String value) {
            addCriterion("zc_produceTime not like", value, "zcProducetime");
            return (Criteria) this;
        }

        public Criteria andZcProducetimeIn(List<String> values) {
            addCriterion("zc_produceTime in", values, "zcProducetime");
            return (Criteria) this;
        }

        public Criteria andZcProducetimeNotIn(List<String> values) {
            addCriterion("zc_produceTime not in", values, "zcProducetime");
            return (Criteria) this;
        }

        public Criteria andZcProducetimeBetween(String value1, String value2) {
            addCriterion("zc_produceTime between", value1, value2, "zcProducetime");
            return (Criteria) this;
        }

        public Criteria andZcProducetimeNotBetween(String value1, String value2) {
            addCriterion("zc_produceTime not between", value1, value2, "zcProducetime");
            return (Criteria) this;
        }

        public Criteria andZcBuytimeIsNull() {
            addCriterion("zc_buyTime is null");
            return (Criteria) this;
        }

        public Criteria andZcBuytimeIsNotNull() {
            addCriterion("zc_buyTime is not null");
            return (Criteria) this;
        }

        public Criteria andZcBuytimeEqualTo(String value) {
            addCriterion("zc_buyTime =", value, "zcBuytime");
            return (Criteria) this;
        }

        public Criteria andZcBuytimeNotEqualTo(String value) {
            addCriterion("zc_buyTime <>", value, "zcBuytime");
            return (Criteria) this;
        }

        public Criteria andZcBuytimeGreaterThan(String value) {
            addCriterion("zc_buyTime >", value, "zcBuytime");
            return (Criteria) this;
        }

        public Criteria andZcBuytimeGreaterThanOrEqualTo(String value) {
            addCriterion("zc_buyTime >=", value, "zcBuytime");
            return (Criteria) this;
        }

        public Criteria andZcBuytimeLessThan(String value) {
            addCriterion("zc_buyTime <", value, "zcBuytime");
            return (Criteria) this;
        }

        public Criteria andZcBuytimeLessThanOrEqualTo(String value) {
            addCriterion("zc_buyTime <=", value, "zcBuytime");
            return (Criteria) this;
        }

        public Criteria andZcBuytimeLike(String value) {
            addCriterion("zc_buyTime like", value, "zcBuytime");
            return (Criteria) this;
        }

        public Criteria andZcBuytimeNotLike(String value) {
            addCriterion("zc_buyTime not like", value, "zcBuytime");
            return (Criteria) this;
        }

        public Criteria andZcBuytimeIn(List<String> values) {
            addCriterion("zc_buyTime in", values, "zcBuytime");
            return (Criteria) this;
        }

        public Criteria andZcBuytimeNotIn(List<String> values) {
            addCriterion("zc_buyTime not in", values, "zcBuytime");
            return (Criteria) this;
        }

        public Criteria andZcBuytimeBetween(String value1, String value2) {
            addCriterion("zc_buyTime between", value1, value2, "zcBuytime");
            return (Criteria) this;
        }

        public Criteria andZcBuytimeNotBetween(String value1, String value2) {
            addCriterion("zc_buyTime not between", value1, value2, "zcBuytime");
            return (Criteria) this;
        }

        public Criteria andZcBuyerIsNull() {
            addCriterion("zc_buyer is null");
            return (Criteria) this;
        }

        public Criteria andZcBuyerIsNotNull() {
            addCriterion("zc_buyer is not null");
            return (Criteria) this;
        }

        public Criteria andZcBuyerEqualTo(String value) {
            addCriterion("zc_buyer =", value, "zcBuyer");
            return (Criteria) this;
        }

        public Criteria andZcBuyerNotEqualTo(String value) {
            addCriterion("zc_buyer <>", value, "zcBuyer");
            return (Criteria) this;
        }

        public Criteria andZcBuyerGreaterThan(String value) {
            addCriterion("zc_buyer >", value, "zcBuyer");
            return (Criteria) this;
        }

        public Criteria andZcBuyerGreaterThanOrEqualTo(String value) {
            addCriterion("zc_buyer >=", value, "zcBuyer");
            return (Criteria) this;
        }

        public Criteria andZcBuyerLessThan(String value) {
            addCriterion("zc_buyer <", value, "zcBuyer");
            return (Criteria) this;
        }

        public Criteria andZcBuyerLessThanOrEqualTo(String value) {
            addCriterion("zc_buyer <=", value, "zcBuyer");
            return (Criteria) this;
        }

        public Criteria andZcBuyerLike(String value) {
            addCriterion("zc_buyer like", value, "zcBuyer");
            return (Criteria) this;
        }

        public Criteria andZcBuyerNotLike(String value) {
            addCriterion("zc_buyer not like", value, "zcBuyer");
            return (Criteria) this;
        }

        public Criteria andZcBuyerIn(List<String> values) {
            addCriterion("zc_buyer in", values, "zcBuyer");
            return (Criteria) this;
        }

        public Criteria andZcBuyerNotIn(List<String> values) {
            addCriterion("zc_buyer not in", values, "zcBuyer");
            return (Criteria) this;
        }

        public Criteria andZcBuyerBetween(String value1, String value2) {
            addCriterion("zc_buyer between", value1, value2, "zcBuyer");
            return (Criteria) this;
        }

        public Criteria andZcBuyerNotBetween(String value1, String value2) {
            addCriterion("zc_buyer not between", value1, value2, "zcBuyer");
            return (Criteria) this;
        }

        public Criteria andZcTypeIsNull() {
            addCriterion("zc_type is null");
            return (Criteria) this;
        }

        public Criteria andZcTypeIsNotNull() {
            addCriterion("zc_type is not null");
            return (Criteria) this;
        }

        public Criteria andZcTypeEqualTo(String value) {
            addCriterion("zc_type =", value, "zcType");
            return (Criteria) this;
        }

        public Criteria andZcTypeNotEqualTo(String value) {
            addCriterion("zc_type <>", value, "zcType");
            return (Criteria) this;
        }

        public Criteria andZcTypeGreaterThan(String value) {
            addCriterion("zc_type >", value, "zcType");
            return (Criteria) this;
        }

        public Criteria andZcTypeGreaterThanOrEqualTo(String value) {
            addCriterion("zc_type >=", value, "zcType");
            return (Criteria) this;
        }

        public Criteria andZcTypeLessThan(String value) {
            addCriterion("zc_type <", value, "zcType");
            return (Criteria) this;
        }

        public Criteria andZcTypeLessThanOrEqualTo(String value) {
            addCriterion("zc_type <=", value, "zcType");
            return (Criteria) this;
        }

        public Criteria andZcTypeLike(String value) {
            addCriterion("zc_type like", value, "zcType");
            return (Criteria) this;
        }

        public Criteria andZcTypeNotLike(String value) {
            addCriterion("zc_type not like", value, "zcType");
            return (Criteria) this;
        }

        public Criteria andZcTypeIn(List<String> values) {
            addCriterion("zc_type in", values, "zcType");
            return (Criteria) this;
        }

        public Criteria andZcTypeNotIn(List<String> values) {
            addCriterion("zc_type not in", values, "zcType");
            return (Criteria) this;
        }

        public Criteria andZcTypeBetween(String value1, String value2) {
            addCriterion("zc_type between", value1, value2, "zcType");
            return (Criteria) this;
        }

        public Criteria andZcTypeNotBetween(String value1, String value2) {
            addCriterion("zc_type not between", value1, value2, "zcType");
            return (Criteria) this;
        }

        public Criteria andZcStatusIsNull() {
            addCriterion("zc_status is null");
            return (Criteria) this;
        }

        public Criteria andZcStatusIsNotNull() {
            addCriterion("zc_status is not null");
            return (Criteria) this;
        }

        public Criteria andZcStatusEqualTo(String value) {
            addCriterion("zc_status =", value, "zcStatus");
            return (Criteria) this;
        }

        public Criteria andZcStatusNotEqualTo(String value) {
            addCriterion("zc_status <>", value, "zcStatus");
            return (Criteria) this;
        }

        public Criteria andZcStatusGreaterThan(String value) {
            addCriterion("zc_status >", value, "zcStatus");
            return (Criteria) this;
        }

        public Criteria andZcStatusGreaterThanOrEqualTo(String value) {
            addCriterion("zc_status >=", value, "zcStatus");
            return (Criteria) this;
        }

        public Criteria andZcStatusLessThan(String value) {
            addCriterion("zc_status <", value, "zcStatus");
            return (Criteria) this;
        }

        public Criteria andZcStatusLessThanOrEqualTo(String value) {
            addCriterion("zc_status <=", value, "zcStatus");
            return (Criteria) this;
        }

        public Criteria andZcStatusLike(String value) {
            addCriterion("zc_status like", value, "zcStatus");
            return (Criteria) this;
        }

        public Criteria andZcStatusNotLike(String value) {
            addCriterion("zc_status not like", value, "zcStatus");
            return (Criteria) this;
        }

        public Criteria andZcStatusIn(List<String> values) {
            addCriterion("zc_status in", values, "zcStatus");
            return (Criteria) this;
        }

        public Criteria andZcStatusNotIn(List<String> values) {
            addCriterion("zc_status not in", values, "zcStatus");
            return (Criteria) this;
        }

        public Criteria andZcStatusBetween(String value1, String value2) {
            addCriterion("zc_status between", value1, value2, "zcStatus");
            return (Criteria) this;
        }

        public Criteria andZcStatusNotBetween(String value1, String value2) {
            addCriterion("zc_status not between", value1, value2, "zcStatus");
            return (Criteria) this;
        }

        public Criteria andZcBzxxIsNull() {
            addCriterion("zc_bzxx is null");
            return (Criteria) this;
        }

        public Criteria andZcBzxxIsNotNull() {
            addCriterion("zc_bzxx is not null");
            return (Criteria) this;
        }

        public Criteria andZcBzxxEqualTo(String value) {
            addCriterion("zc_bzxx =", value, "zcBzxx");
            return (Criteria) this;
        }

        public Criteria andZcBzxxNotEqualTo(String value) {
            addCriterion("zc_bzxx <>", value, "zcBzxx");
            return (Criteria) this;
        }

        public Criteria andZcBzxxGreaterThan(String value) {
            addCriterion("zc_bzxx >", value, "zcBzxx");
            return (Criteria) this;
        }

        public Criteria andZcBzxxGreaterThanOrEqualTo(String value) {
            addCriterion("zc_bzxx >=", value, "zcBzxx");
            return (Criteria) this;
        }

        public Criteria andZcBzxxLessThan(String value) {
            addCriterion("zc_bzxx <", value, "zcBzxx");
            return (Criteria) this;
        }

        public Criteria andZcBzxxLessThanOrEqualTo(String value) {
            addCriterion("zc_bzxx <=", value, "zcBzxx");
            return (Criteria) this;
        }

        public Criteria andZcBzxxLike(String value) {
            addCriterion("zc_bzxx like", value, "zcBzxx");
            return (Criteria) this;
        }

        public Criteria andZcBzxxNotLike(String value) {
            addCriterion("zc_bzxx not like", value, "zcBzxx");
            return (Criteria) this;
        }

        public Criteria andZcBzxxIn(List<String> values) {
            addCriterion("zc_bzxx in", values, "zcBzxx");
            return (Criteria) this;
        }

        public Criteria andZcBzxxNotIn(List<String> values) {
            addCriterion("zc_bzxx not in", values, "zcBzxx");
            return (Criteria) this;
        }

        public Criteria andZcBzxxBetween(String value1, String value2) {
            addCriterion("zc_bzxx between", value1, value2, "zcBzxx");
            return (Criteria) this;
        }

        public Criteria andZcBzxxNotBetween(String value1, String value2) {
            addCriterion("zc_bzxx not between", value1, value2, "zcBzxx");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zc_info
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 29 15:27:41 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zc_info
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}