package com.jianxilin.ssm.entity;

public class ZcInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_info.zc_id
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String zcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_info.zc_no
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String zcNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_info.zc_name
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String zcName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_info.zc_price
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private Float zcPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_info.zc_factory
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String zcFactory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_info.zc_produceTime
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String zcProducetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_info.zc_buyTime
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String zcBuytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_info.zc_buyer
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String zcBuyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_info.zc_type
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String zcType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_info.zc_status
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String zcStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_info.zc_bzxx
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String zcBzxx;

    @Override
    public String toString() {
        return "ZcInfo{" +
                "zcId='" + zcId + '\'' +
                ", zcNo='" + zcNo + '\'' +
                ", zcName='" + zcName + '\'' +
                ", zcPrice=" + zcPrice +
                ", zcFactory='" + zcFactory + '\'' +
                ", zcProducetime='" + zcProducetime + '\'' +
                ", zcBuytime='" + zcBuytime + '\'' +
                ", zcBuyer='" + zcBuyer + '\'' +
                ", zcType='" + zcType + '\'' +
                ", zcStatus='" + zcStatus + '\'' +
                ", zcBzxx='" + zcBzxx + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_info.zc_id
     *
     * @return the value of zc_info.zc_id
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getZcId() {
        return zcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_info.zc_id
     *
     * @param zcId the value for zc_info.zc_id
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setZcId(String zcId) {
        this.zcId = zcId == null ? null : zcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_info.zc_no
     *
     * @return the value of zc_info.zc_no
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getZcNo() {
        return zcNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_info.zc_no
     *
     * @param zcNo the value for zc_info.zc_no
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setZcNo(String zcNo) {
        this.zcNo = zcNo == null ? null : zcNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_info.zc_name
     *
     * @return the value of zc_info.zc_name
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getZcName() {
        return zcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_info.zc_name
     *
     * @param zcName the value for zc_info.zc_name
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setZcName(String zcName) {
        this.zcName = zcName == null ? null : zcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_info.zc_price
     *
     * @return the value of zc_info.zc_price
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public Float getZcPrice() {
        return zcPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_info.zc_price
     *
     * @param zcPrice the value for zc_info.zc_price
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setZcPrice(Float zcPrice) {
        this.zcPrice = zcPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_info.zc_factory
     *
     * @return the value of zc_info.zc_factory
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getZcFactory() {
        return zcFactory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_info.zc_factory
     *
     * @param zcFactory the value for zc_info.zc_factory
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setZcFactory(String zcFactory) {
        this.zcFactory = zcFactory == null ? null : zcFactory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_info.zc_produceTime
     *
     * @return the value of zc_info.zc_produceTime
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getZcProducetime() {
        return zcProducetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_info.zc_produceTime
     *
     * @param zcProducetime the value for zc_info.zc_produceTime
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setZcProducetime(String zcProducetime) {
        this.zcProducetime = zcProducetime == null ? null : zcProducetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_info.zc_buyTime
     *
     * @return the value of zc_info.zc_buyTime
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getZcBuytime() {
        return zcBuytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_info.zc_buyTime
     *
     * @param zcBuytime the value for zc_info.zc_buyTime
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setZcBuytime(String zcBuytime) {
        this.zcBuytime = zcBuytime == null ? null : zcBuytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_info.zc_buyer
     *
     * @return the value of zc_info.zc_buyer
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getZcBuyer() {
        return zcBuyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_info.zc_buyer
     *
     * @param zcBuyer the value for zc_info.zc_buyer
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setZcBuyer(String zcBuyer) {
        this.zcBuyer = zcBuyer == null ? null : zcBuyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_info.zc_type
     *
     * @return the value of zc_info.zc_type
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getZcType() {
        return zcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_info.zc_type
     *
     * @param zcType the value for zc_info.zc_type
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setZcType(String zcType) {
        this.zcType = zcType == null ? null : zcType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_info.zc_status
     *
     * @return the value of zc_info.zc_status
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getZcStatus() {
        return zcStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_info.zc_status
     *
     * @param zcStatus the value for zc_info.zc_status
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setZcStatus(String zcStatus) {
        this.zcStatus = zcStatus == null ? null : zcStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_info.zc_bzxx
     *
     * @return the value of zc_info.zc_bzxx
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getZcBzxx() {
        return zcBzxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_info.zc_bzxx
     *
     * @param zcBzxx the value for zc_info.zc_bzxx
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setZcBzxx(String zcBzxx) {
        this.zcBzxx = zcBzxx == null ? null : zcBzxx.trim();
    }
}