package com.jianxilin.ssm.entity;

public class ZcWx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_wx.repair_no
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private Integer repairNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_wx.zc_id
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String zcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_wx.send_time
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_wx.sender
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_wx.login_user
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String loginUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_wx.reason
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_wx.wx_time
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String wxTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_wx.wx_result
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String wxResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_wx.cost
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private Float cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_wx.wx_comment
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    private String wxComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_wx.repair_no
     *
     * @return the value of zc_wx.repair_no
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public Integer getRepairNo() {
        return repairNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_wx.repair_no
     *
     * @param repairNo the value for zc_wx.repair_no
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setRepairNo(Integer repairNo) {
        this.repairNo = repairNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_wx.zc_id
     *
     * @return the value of zc_wx.zc_id
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getZcId() {
        return zcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_wx.zc_id
     *
     * @param zcId the value for zc_wx.zc_id
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setZcId(String zcId) {
        this.zcId = zcId == null ? null : zcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_wx.send_time
     *
     * @return the value of zc_wx.send_time
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_wx.send_time
     *
     * @param sendTime the value for zc_wx.send_time
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setSendTime(String sendTime) {
        this.sendTime = sendTime == null ? null : sendTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_wx.sender
     *
     * @return the value of zc_wx.sender
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_wx.sender
     *
     * @param sender the value for zc_wx.sender
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setSender(String sender) {
        this.sender = sender == null ? null : sender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_wx.login_user
     *
     * @return the value of zc_wx.login_user
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getLoginUser() {
        return loginUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_wx.login_user
     *
     * @param loginUser the value for zc_wx.login_user
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setLoginUser(String loginUser) {
        this.loginUser = loginUser == null ? null : loginUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_wx.reason
     *
     * @return the value of zc_wx.reason
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_wx.reason
     *
     * @param reason the value for zc_wx.reason
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_wx.wx_time
     *
     * @return the value of zc_wx.wx_time
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getWxTime() {
        return wxTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_wx.wx_time
     *
     * @param wxTime the value for zc_wx.wx_time
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setWxTime(String wxTime) {
        this.wxTime = wxTime == null ? null : wxTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_wx.wx_result
     *
     * @return the value of zc_wx.wx_result
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getWxResult() {
        return wxResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_wx.wx_result
     *
     * @param wxResult the value for zc_wx.wx_result
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setWxResult(String wxResult) {
        this.wxResult = wxResult == null ? null : wxResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_wx.cost
     *
     * @return the value of zc_wx.cost
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public Float getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_wx.cost
     *
     * @param cost the value for zc_wx.cost
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setCost(Float cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_wx.wx_comment
     *
     * @return the value of zc_wx.wx_comment
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public String getWxComment() {
        return wxComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_wx.wx_comment
     *
     * @param wxComment the value for zc_wx.wx_comment
     *
     * @mbg.generated Wed Apr 29 15:27:41 CST 2020
     */
    public void setWxComment(String wxComment) {
        this.wxComment = wxComment == null ? null : wxComment.trim();
    }
}